// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktyqsarxhhhaorcehquj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0eXFzYXJ4aGhoYW9yY2VocXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjAyODQsImV4cCI6MjA3MDU5NjI4NH0.hNqBa-R85tLgF4YOLrDzrQBAo98PIwGvApjXxCywLuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});